pipeline:
  build:
    image: node:6.9
    commands:
        - npm install --silent
        - npm run --silent build || true
        - npm run test

  publish:
    image: plugins/docker
    repo: ecsdevops/aurora-gateway
    username: ecsdevops
    password: ${DOCKER_PASSWORD}
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}

services:
  redis:
    image: redis:alpine
  rabbit:
    image: rabbitmq:alpine
