pipeline:
  build:
    image: node:6.9
    commands:
        - npm install --silent
        - npm run --silent build || true
        - npm run test

  publish:
    image: plugins/docker
    repo: ecsdevops/aurora-manager
    tags: 
      - "latest"
      - ${DRONE_COMMIT_SHA}
    username: ecsdevops
    password: ${DOCKER_PASSWORD}

services:
  rabbit:
    image: rabbitmq:alpine
